### ISSUE TITLE
Как-то ничего нет

### ISSUE THREAD

**Issue by nzinov** [PKoshkin/geo#1]

**Comment by PKoshkin** [comment]
Чет не пушилось :) Там яваскриптовые библиотеки, я их тоже добавил, а надо
удалить, наверное.

15 июл. 2017 г. 5:23 ПП пользователь "Nikolay Zinov" <
notifications@github.com> написал:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PKoshkin/geo/issues/1>, or mute the thread

**Comment by nzinov** [comment]
Submodule сделай
